version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "slack-support-bot-node-modules-layer"
s3_bucket = "sam.huge.head.li"
s3_prefix = "slack-support-bot-node-modules-layer"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"